#:schema https://rlbot.org/schemas/agent.json
[settings]
name = "Scratch Example Bot"
# Should be [your name]/[your bots name]
agent_id = "rlbot/scratch-example/atba_agent"
# loadout_file = "loadout.toml"
run_command = "rlbot-scratch-bridge.exe --sb3 project.sb3"
run_command_linux = "./rlbot-scratch-bridge --sb3 project.sb3"
hivemind = false

[details]
description = "Scratch always-towards-ball-agent."
# fun_fact = ""
# source_link = "https://github.com/RLBot/scratch-interface"
developer = ""
language = "Scratch (TurboWarp)"
# logo_file = "logo.png"
# ALL POSSIBLE TAGS: 1v1, teamplay, goalie, hoops, dropshot, snow-day, spike-rush, heatseaker, memebot
# NOTE: Only add the goalie tag if your bot only plays as a goalie; this directly contrasts with the teamplay tag!
# NOTE: Only add a tag for a special game mode if you bot properly supports it
tags = []
